#!/usr/bin/env bash

mantain_locals=false
full_install=false
minimal_install=false

while (($# > 0)); do
    if [[ $1 == --* ]]; then
        case $1 in
            --minimal)
                minimale_install=true
                ;;
            --full)
                full_install=true
                ;;
            --presevre)
                preserve_locals=true
                ;;
            --help)
                usage
                exit 0
                ;;
            *)
                echo "Unknown option $1" >&2
                usage >&2
                exit 64
            ;;
        esac
    elif [[ $1 == -* ]]; then
        opt_len=${#1}
        for ((char = 1; char < opt_len; char++)); do
            opt=${1:char:1}
            case opt in
                h)
                    usage
                    exit 0
                    ;;
                m)
                    minimale_install=true
                    ;;
                f)
                    full_install=true
                    ;;
                p)
                    preserve_locals=true
                    ;;
                *)
                    echo "Unknown option -$1" >&2
                    usage >&2
                    exit 64
                    ;;
            esac
        done
    else
        echo "Unknown option $1" >&2
        usage >&2
        exit 64
    fi
    shift
done

if [[ -f ~/.bashrc ]]; then
    if $mantain_locals; then
        cp ~/.bashrc ~/.bashrc.local
    else
        rm  ~/.bashrc
    fi
fi
if [[ -f ~/.bash_aliases ]]; then
    if $mantain_locals; then
        mkdir -p ~/.bash_aliases.d
        cp ~/.bash_alias ~/.bash_aliases.d/bash_aliases.local
    else
        rm  ~/.bash_aliases
    fi
fi

ln bashrc ~/.bashrc
ln bash_aliases ~/.bash_aliases

$minimal_install && exit 0

if [[ -f ~/.config/nvim/init.lua ]]; then 
    rm ~/.config/nvim/init.lua
fi

ln nvim/init.lua ~/.config/nvim/init.lua

$full_install || exit 0

./bem/bem/bem init > /dev/null
error=$0
if ((error != 0)); then
    echo "ERROR: cannot install bem" >&2
    exit $error
fi

