#!/usr/bin/env bash

preserve_locals=false
full_install=false
minimal_install=false

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Install configuration files and optional components.

Options:
  -m, --minimal       Perform only the minimal installation
  -f, --full          Perform the full installation, including BEM
  -p, --preserve      Preserve existing local configuration files
  -h, --help          Show this help message and exit

Examples:
  $(basename "$0")
  $(basename "$0") --minimal
  $(basename "$0") --full --preserve
  $(basename "$0") -fp
EOF
}

while (($# > 0)); do
    if [[ $1 == --* ]]; then
        case "$1" in
            --minimal)
                minimal_install=true
                ;;
            --full)
                full_install=true
                ;;
            --preserve)
                preserve_locals=true
                ;;
            --help)
                usage
                exit 0
                ;;
            *)
                echo "Unknown option: $1" >&2
                usage >&2
                exit 64
                ;;
        esac

    elif [[ $1 == -* ]]; then
        opt_len=${#1}

        for ((char = 1; char < opt_len; char++)); do
            opt=${1:char:1}

            case "$opt" in
                h)
                    usage
                    exit 0
                    ;;
                m)
                    minimal_install=true
                    ;;
                f)
                    full_install=true
                    ;;
                p)
                    preserve_locals=true
                    ;;
                *)
                    echo "Unknown option: -$opt" >&2
                    usage >&2
                    exit 64
                    ;;
            esac
        done

    else
        echo "Unknown argument: $1" >&2
        usage >&2
        exit 64
    fi

    shift
done


# bashrc

if [[ -f ~/.bashrc ]]; then
    if $preserve_locals; then
        cp ~/.bashrc ~/.bashrc.local
    else
        rm ~/.bashrc
    fi
fi


# bash aliases

if [[ -f ~/.bash_aliases ]]; then
    if $preserve_locals; then
        mkdir -p ~/.bash_aliases.d
        cp ~/.bash_aliases ~/.bash_aliases.d/bash_aliases.local
    else
        rm ~/.bash_aliases
    fi
fi


# Install bash configuration

ln -s bashrc ~/.bashrc
ln -s bash_aliases ~/.bash_aliases


# Minimal installation stops here

$minimal_install && exit 0


# Neovim

mkdir -p ~/.config/nvim

if [[ -f ~/.config/nvim/init.lua ]]; then
    rm ~/.config/nvim/init.lua
fi

ln -s nvim/init.lua ~/.config/nvim/init.lua


# Standard installation stops here

$full_install || exit 0


# Full installation: BEM

./bem/bem/bem init > /dev/null
error=$?

if (( error != 0 )); then
    echo "ERROR: cannot install bem" >&2
    exit "$error"
fi
